config/routes.rb
require 'domain_constraint'

Rails.application.routes.draw do
  constraints DomainConstraint.new('dima') do
    root :to => 'recipes#index'
  end
  post '/rate' => 'rater#create', :as => 'rate'

  resources :recipes do
    resources :comment_blocks
  end

  resources :posts do
    resources :comment_blocks
  end

  resources :foodiye_posts , :path => "pins" do
    resources :comment_blocks
  end


  resources :post_collaborators
  resources :user_collaborators

  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  get 'users' => 'foodiye_posts#members'
  get 'get_title' => 'foodiye_posts#get_title'
  get 'hand/:id' => 'handler#hand'
  get 'tags/:tag', to: 'posts#index', as: 'tag'
  get 'authors/:user_nicename' => 'posts#authors', as: 'authors'
  get 'category/:slug' => 'posts#categories', as: 'category'
  post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users, :only => [:show]
  get '/posts/versions/history/:id' => 'versions#history', as: :posts_history
  get '/posts/:id/edit/:version_id' => 'posts#edit', as: :posts_version
  get '/recipes/:id/edit/:version_id' => 'recipes#edit', as: :recipes_version

  scope  'admin' do
  get '/dashboard' => 'admin_panel#main_page'
  get '/black_list_domain' => 'admin_panel#black_list'
  post '/black_list_domain' => 'admin_panel#add_black_list'
  delete '/black_list_domain' => 'admin_panel#destroy_black_list', :as => 'destroy'
  end

  get 'results', to: 'results#index', as: 'results'

  mount SimpleFormMarkdownEditor::Engine => "/"
  #reputation system
  delete  'likes/:resource_name/:resource_id' => 'likes#destroy', :as => 'unlike'
  post    'likes/:resource_name/:resource_id' => 'likes#create',  :as => 'like'

end

app/views/shared/foodiye/_footer_foodiye.html.erb
<div class="footer">
  <div class="wrap">
    <p> <p> © 2016. Developed by </p> </p>
  </div>
</div>

app/views/shared/foodiye/_form_edit_foodiye.html.erb
<div class="container">
  <div class="wrap">
    <div class="single-page">
      <p id="notice"> <%= notice %> </p>
      <%= link_to 'Back', foodiye_posts_path %>
      <fieldset>
        <!-- Form Name -->
        <legend>Edit post</legend>
        <div class="tab-content">
          <% if @foodiye_post.post_type == "topic" %>
              <%= simple_form_for(@foodiye_post) do |f| %>
                  <%= f.error_notification %>
                  <div class="form-inputs">
                    <%= f.input :title %>
                    <%= f.input :description %>
                    <%= f.hidden_field :post_type, :value => "topic" %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>
                    <%= f.button :submit, "Publish", class: 'btn btn-primary' %>
                  </div>
              <% end %>
          <% elsif @foodiye_post.post_type == "photo" %>
              <%= simple_form_for(@foodiye_post) do |f| %>
                  <%= f.error_notification %>
                  <div class="form-inputs">
                    <%= f.input :title %>
                    <%= f.input :photo_link %>
                    <%= f.input :attachment, as: :file %>
                    <%= f.input :description %>
                    <%= f.hidden_field :post_type, :value => "photo" %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>
                    <%= f.button :submit, "Publish", class: 'btn btn-primary' %>
                  </div>
              <% end %>
          <% else
               @foodiye_post.post_type == "video" %>
              <%= simple_form_for(@foodiye_post) do |f| %>
                  <%= f.error_notification %>
                  <div class="form-inputs">
                    <%= f.input :video_url %>
                    <%= f.input :title %>
                    <%= f.input :description %>
                    <%= f.hidden_field :post_type, :value => "video" %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>
                    <%= f.button :submit, "Publish", class: 'btn btn-primary' %>
                  </div>
              <% end %>
          <% end %>
          </div>
      </fieldset>
    </div>
  </div>
</div>

app/views/shared/foodiye/_form_foodiye.html.erb
<div class="container">
  <div class="wrap">
    <div class="single-page">
      <p id="notice"> <%= notice %> </p>
      <%= link_to 'Back', foodiye_posts_path %>
      <fieldset>
        <!-- Form Name -->
        <legend>Create post</legend>
        <ul class="nav nav-tabs">
          <li class="active"><a href="#topic" data-toggle="tab">Topic</a></li>
          <li><a href="#photo" data-toggle="tab">Photo</a></li>
          <li><a href="#video" data-toggle="tab">Video</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane active" id="topic">
            <%= simple_form_for(@foodiye_post) do |f| %>
              <%= f.error_notification %>
              <div class="form-inputs">
                <%= f.input :title %>
                <%= f.input :description %>
                <%= f.hidden_field :post_type, :value => "topic" %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.button :submit, "Publish", class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>

          <div class="tab-pane" id="photo">
            <button id="suggest" style="display: none;">suggest title</button>
            <%= simple_form_for(@foodiye_post) do |f| %>
              <%= f.error_notification %>
              <div class="form-inputs">
                <%= f.input :title, input_html: {id: "value"} %>
                <%= f.input :photo_link, input_html: {id: "test"} %>
                <%= f.input :attachment, as: :file %>
                <%= f.input :description %>
                <%= f.hidden_field :post_type, :value => "photo" %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.button :submit, "Publish", class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
          <div class="tab-pane" id="video">
            <%= simple_form_for(@foodiye_post) do |f| %>
              <%= f.error_notification %>
              <div class="form-inputs">
                <%= f.input :video_url %>
                <%= f.input :title %>
                <%= f.input :description %>
                <%= f.hidden_field :post_type, :value => "video" %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.button :submit, "Publish", class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
          <div class="tab-pane" id="settings">...</div>
        </div>
      </fieldset>
    </div>
  </div>
</div>

<script>
  $("#test").on("keyup", function() {
    var url = $("#test").val();
    $.ajax({
      url : "<%= get_title_path %>",
      type : "get",
      data : { data_value: url },
      success: function(data,status,xhr){
        if (data && (data.message != "no title suggested")) {
          $("#suggest").show();
          document.getElementById('suggest').onclick=function(){
            document.getElementById("value").value = data.message;
          };
        };
      },
    });
  });
</script>

app/views/shared/foodiye/_header_foodiye.erb
<div class="header">
  <div class="wrap">
    <div class="logo">
      <%#= image_tag ('foodiye/foodiye_logo.png') %>
    </div>
    <div class="nav-icon">
      <a href="#" class="right_bt" id="activator"><span> </span> </a>
    </div>
    <div class="box" id="box">
      <div class="box_content">
        <div class="box_content_center">
          <div class="form_content">
            <div class="menu_box_list">
              <ul>
                <li> <%= link_to 'About', foodiye_posts_path %> </li>
                <div class="clear"></div>
              </ul>
            </div>

            <a class="boxclose" id="boxclose"> <span> </span></a>
          </div>
        </div>
      </div>
    </div>
    <div class="top-searchbar">
      <form>
        <input type="text"/><input type="submit" value=""/>
      </form>
    </div>
    <div class="create-post">
      <% if user_signed_in? %>
        <%= link_to " Create post", new_foodiye_post_path %>
      <% end %>
      <% unless user_signed_in? %>
        <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <button href="#" class="dropdown-toggle btn btn-default navbar-btn btn-lg" data-toggle="dropdown" id="pricing-btn" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.user_nicename %> <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Home',  foodiye_posts_path %></li>
                <li><%= link_to 'Profile', user_path(current_user) %></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
    <!--start modal-->
    <script>(function (d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s);
      js.id = id;
      js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.7&appId=318379988503662";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <script>
      $(window).on('scroll',function(e){
        if (this.scrollY> 0) {
          $("nav.navbar").addClass("nav-scroll");
        } else {
          $("nav.navbar").removeClass("nav-scroll");
        }
      });
    </script>
  </div>
</div>