config/routes.rb
require 'domain_constraint'

Rails.application.routes.draw do
  constraints DomainConstraint.new('dima') do
    root :to => 'recipes#index'
  end
  post '/rate' => 'rater#create', :as => 'rate'

  resources :recipes do
    resources :comment_blocks
  end

  resources :posts do
    resources :comment_blocks
  end

  resources :foodiye_posts , :path => "pins" do
    resources :comment_blocks
  end


  resources :post_collaborators
  resources :user_collaborators

  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  get 'users' => 'foodiye_posts#members'
  get 'get_title' => 'foodiye_posts#get_title'
  get 'hand/:id' => 'handler#hand'
  get 'tags/:tag', to: 'posts#index', as: 'tag'
  get 'authors/:user_nicename' => 'posts#authors', as: 'authors'
  get 'category/:slug' => 'posts#categories', as: 'category'
  post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users, :only => [:show]
  get '/posts/versions/history/:id' => 'versions#history', as: :posts_history
  get '/posts/:id/edit/:version_id' => 'posts#edit', as: :posts_version
  get '/recipes/:id/edit/:version_id' => 'recipes#edit', as: :recipes_version

  scope  'admin' do
  get '/dashboard' => 'admin_panel#main_page'
  get '/black_list_domain' => 'admin_panel#black_list'
  post '/black_list_domain' => 'admin_panel#add_black_list'
  delete '/black_list_domain' => 'admin_panel#destroy_black_list', :as => 'destroy'
  end

  get 'results', to: 'results#index', as: 'results'

  mount SimpleFormMarkdownEditor::Engine => "/"
  #reputation system
  delete  'likes/:resource_name/:resource_id' => 'likes#destroy', :as => 'unlike'
  post    'likes/:resource_name/:resource_id' => 'likes#create',  :as => 'like'

end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController

  def index

  end

  def new
    @post_collaborator = PostCollaborator.new
    @user_collaborator = UserCollaborator.new
  end

  def main_page

    filter = params[:filter]
    if filter.blank?
      @posts = Post.all
                   .order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    elsif filter == 'all_posts'
      @posts = Post.all
                   .order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    elsif filter == 'my_posts'
      @posts = Post.where(user_id: current_user.id)
                   .order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    elsif filter == 'all_recipes'
      @recipes = Recipe.all
                   .order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    elsif filter == 'my_recipes'
      @recipes = Recipe.where(user_id: current_user.id)
                   .order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    elsif filter == 'assigned_to_me'
      @posts = Post.where(user_id: current_user.id)
                   .order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    elsif filter == 'with_comments'
      @posts = Post.joins(:comment_blocks).distinct.where('comment_blocks.user_id' => current_user.id).order("created_at DESC")
      @recipes = Recipe.joins(:comment_blocks).distinct.where('comment_blocks.user_id' => current_user.id).order("created_at DESC")

    end
  end
  def black_list
    @blacklists = Blacklist.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def add_black_list
    @blacklist = Blacklist.new(blacklist_params_params)
    if
    @blacklist.save
      redirect_to black_list_domain_path, notice: "New domain has been added to blacklist"
    else
      render 'admin_panel/black_list'
      end
  end

  def destroy_black_list
    @blacklist = Blacklist.find(params[:id])
    @blacklist.destroy
    redirect_to black_list_domain_path, notice: "Domain has been deleted from blacklist"
  end

  private
  def blacklist_params_params
    params.fetch(:blacklist).permit!
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/views/admin_panel/black_list.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>ChefatLarge</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <style>
    ul.hr {
      margin: 0; /* Обнуляем значение отступов */
      padding: 4px; /* Значение полей */
    }
    ul.hr li  {
      color: lightslategray;
      display: inline; /* Отображать как строчный элемент */
      box-sizing: border-box;
      display: inline-block;
      margin: 0;
      padding: 1px 7px;
      border: 1px solid transparent;
      border-radius: 3px;
      font-size: 110%;
      text-decoration: none;
      /*color: #3572b0;*/
    }
  </style>
</head>
<body>
  <p id="notice"><%= notice %></p>
<div id="wrapper">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="max-height: 50px" >
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" > Dashboard </a>
  </div>
  <!-- /.navbar-header -->
  <ul class="nav navbar-top-links navbar-right">
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li>
          <i class="fa fa-dashboard fa-fw">Actions</i>
        </li>
        <li>
          <%=link_to 'Blacklist Domains', black_list_domain_path %>
        </li>

      </ul>
    </div>
  </div>
  </nav>
  <div id="page-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <!--<h1 class="page-header"> </h1>-->
        <div class="page-header">
          <div class = "text-right link-style">
            <% blacklist = Blacklist.new %>
            <%= form_for blacklist, :url => {:action => "add_black_list"} do |f| %>
              <h4> www. <%= f.text_field :domain %>
               <%= f.submit 'Add to blacklist' %> </h4>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <table class="table">
          <thead>
          <tr class="table-links-title">
            <th width="50%"> Domain </th>
            <th> Created at </th>
            <!--<th width="20%"> Destroy </th>-->
          </tr>
          </thead>
          <tbody>
          <% @blacklists.each do |blacklist| %>
            <tr class="table-links">
              <td width="50%"> <%= blacklist.domain %> </td>
              <td> <%= blacklist.created_at %> </td>
              <!--<td width="20%"><%#= link_to 'Destroy', destroy_path(blacklist),
                              method: :delete,
                              data: { confirm: 'Are you sure?' } %></td>-->
            </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <%= will_paginate @blacklists %>
  </div>

  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</div>
</body>
</html>

app/views/admin_panel/main_page.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>ChefatLarge</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <style>
    ul.hr {
      margin: 0; /* Обнуляем значение отступов */
      padding: 4px; /* Значение полей */
    }
    ul.hr li  {
      color: lightslategray;
      display: inline; /* Отображать как строчный элемент */
      box-sizing: border-box;
      display: inline-block;
      margin: 0;
      padding: 1px 7px;
      border: 1px solid transparent;
      border-radius: 3px;
      font-size: 110%;
      text-decoration: none;
      /*color: #3572b0;*/
    }
  </style>
</head>
<body>
  <p id="notice"><%= notice %></p>
<div id="wrapper">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="max-height: 50px" >
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" > Dashboard </a>
  </div>
  <!-- /.navbar-header -->
  <ul class="nav navbar-top-links navbar-right">
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li>
          <i class="fa fa-dashboard fa-fw">Actions</i>
        </li>
        <li>
          <%=link_to 'Blacklist Domains', black_list_domain_path %>
        </li>

      </ul>
    </div>
  </div>
  </nav>
  <div id="page-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <!--<h1 class="page-header"> </h1>-->
        <div class="page-header">
          <div class = "text-right link-style">
            <%= link_to 'Create new post', new_post_path %>
            <%= link_to 'Create new recipe', new_recipe_path %>
          </div>
            <div class="link-style">
              <ul class="hr">
                <li class="filter-status">FILTERS:</li>
                <li> <%= link_to 'All posts', dashboard_path(filter: 'all_posts') %>  </li>
                <li> <%= link_to 'My posts', dashboard_path(filter: 'my_posts') %></li>
                <li> <%= link_to 'All recipes', dashboard_path(filter: 'all_recipes') %>  </li>
                <li> <%= link_to 'My recipes', dashboard_path(filter: 'my_recipes') %></li>
                <!--<li> <%#= link_to 'Assigned to me', dashboard_path(filter: 'assigned_to_me') %></li>-->
                <li> <%= link_to 'With comments', dashboard_path(filter: 'with_comments') %> </li>
              </ul>
            </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <table class="table">
          <thead>
          <tr class="table-links-title">
            <th width="30%"><%= link_to 'Title', dashboard_path(:sort => 'title', :filter => params[:filter]) %> </th>
            <th> <%= link_to 'Post status', dashboard_path(sort: 'post_status', :filter => params[:filter]) %> </th>
            <th> <%= link_to 'Assignee', dashboard_path(sort: 'title', :filter => params[:filter]) %> </th>
            <th> <%= link_to 'Created', dashboard_path(sort: 'created_at', :filter => params[:filter]) %> </th>
            <th> <%= link_to 'Updates', dashboard_path(sort: 'updated_at', :filter => params[:filter]) %> </th>
          </tr>
          </thead>
          <tbody>
          <% if params[:filter]  == 'all_posts' or params[:filter]  == 'my_posts' or params[:filter].blank?%>
            <% unless @posts.nil? %>
              <% @posts.each do |post| %>
                <tr class="table-links">
                  <td width="30%"> <%= link_to post.title, edit_post_path(post) %> </td>
                  <td> <%= post.post_status %> </td>
                  <td> Grinko Dmytro </td>
                  <td> <%= post.created_at %> </td>
                  <td> <%= post.updated_at %> </td>
                </tr>
              <% end %>
            <% end %>
          <% elsif params[:filter]  == 'all_recipes' or params[:filter]  == 'my_recipes'%>
            <% unless @recipes.nil? %>
              <% @recipes.each do |post| %>
                <tr class="table-links">
                  <td width="30%"> <%= link_to post.title, edit_recipe_path(post) %> </td>
                  <td> <%= post.post_status %> </td>
                  <td> Grinko Dmytro </td>
                  <td> <%= post.created_at %> </td>
                  <td> <%= post.updated_at %> </td>
                </tr>
              <% end %>
            <% end %>
          <% elsif params[:filter]  == 'with_comments' %>
            <% unless @posts.nil? %>
              <% @posts.each do |post| %>
                <tr class="table-links">
                  <td width="30%"> <%= link_to post.title, edit_post_path(post) %> </td>
                  <td> <%= post.post_status %> </td>
                  <td> Grinko Dmytro </td>
                  <td> <%= post.created_at %> </td>
                  <td> <%= post.updated_at %> </td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <% if params[:filter]  == 'all_posts' or params[:filter]  == 'my_posts' or params[:filter].blank?%>
      <% unless params[:filter]  == 'with_comments'%>
        <%= will_paginate @posts %>
      <% end %>
    <% elsif params[:filter]  == 'all_recipes' or params[:filter]  == 'my_recipes'%>
      <%= will_paginate @recipes %>
    <% end %>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</div>
</body>
</html>