config/routes.rb
require 'domain_constraint'

Rails.application.routes.draw do
  constraints DomainConstraint.new('dima') do
    root :to => 'recipes#index'
  end
  post '/rate' => 'rater#create', :as => 'rate'

  resources :recipes do
    resources :comment_blocks
  end

  resources :posts do
    resources :comment_blocks
  end

  resources :foodiye_posts , :path => "pins" do
    resources :comment_blocks
  end


  resources :post_collaborators
  resources :user_collaborators

  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  get 'users' => 'foodiye_posts#members'
  get 'get_title' => 'foodiye_posts#get_title'
  get 'hand/:id' => 'handler#hand'
  get 'tags/:tag', to: 'posts#index', as: 'tag'
  get 'authors/:user_nicename' => 'posts#authors', as: 'authors'
  get 'category/:slug' => 'posts#categories', as: 'category'
  post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users, :only => [:show]
  get '/posts/versions/history/:id' => 'versions#history', as: :posts_history
  get '/posts/:id/edit/:version_id' => 'posts#edit', as: :posts_version
  get '/recipes/:id/edit/:version_id' => 'recipes#edit', as: :recipes_version

  scope  'admin' do
  get '/dashboard' => 'admin_panel#main_page'
  get '/black_list_domain' => 'admin_panel#black_list'
  post '/black_list_domain' => 'admin_panel#add_black_list'
  delete '/black_list_domain' => 'admin_panel#destroy_black_list', :as => 'destroy'
  end

  get 'results', to: 'results#index', as: 'results'

  mount SimpleFormMarkdownEditor::Engine => "/"
  #reputation system
  delete  'likes/:resource_name/:resource_id' => 'likes#destroy', :as => 'unlike'
  post    'likes/:resource_name/:resource_id' => 'likes#create',  :as => 'like'

end

app/views/shared/_article_block.erb
<article>
  <!-- Blog item Start -->
  <div class="blog-item-wrap">
    <!-- Post Format icon Start -->
    <div class="post-format">
      <span><i class="ico-bookmark"></i></span>
    </div>
    <!-- Post Format icon End -->
    <% if post.class == Post %>
      <h2> <%= link_to post.title, post_path(post) %> </h2>
    <% else %>
      <h2> <%= link_to post.title, recipe_path(post) %> </h2>
    <% end %>
    <!-- Entry Meta Start-->
    <div class="entry-meta">
      <% unless post.user.blank? %>
        <span class="meta-part"><i class="ico-user"></i> <%= link_to post.user.user_nicename, authors_path(post.user.user_nicename) %> </span>
      <% end %>
      <span class="meta-part"><i class="ico-calendar-alt-fill"></i>  </span> <%= post.created_at %>
      <span class="meta-part"><i class="ico-tag"></i>Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></span>
      <% unless post.category.blank? %>
        <span class="meta-part"><i class="ico-tag"></i> Category: <%= link_to post.category.name, category_path(post.category.slug) %> </span>
      <% end %>
      <% if check_current_user? %>
        <span class="meta-part"><i class="ico-tag"></i> Status: </span><%= post.post_status %>
      <% end %>
      <!--class="ico-tag"  class="ico-comments-->
    </div><!-- Entry Meta End-->
    <!-- Feature inner Start -->
    <div class="feature-inner">
    </div><!-- Feature inner End -->
    <!-- Post Content Start -->
    <div class="post-content">
      <p> <% post.attachments.where(main_image: "yes").each do |attachment| %>
        <%= image_tag attachment.attachment.url %> <% end %></p>
      <p><%= raw post.content %> </p>
    </div><!-- Post Content End -->
    <div class="entry-more">
      <% if check_current_user? %>
        <div class="pull-left">
          <% if controller.controller_name == 'recipes' %>
              <a class="btn btn-common" href="<%=edit_recipe_path(post)%>">Edit <i class="ico-arrow-right"></i></a>
          <% else %>
              <a class="btn btn-common" href="<%=edit_post_path(post)%>">Edit <i class="ico-arrow-right"></i></a>
          <% end %>
        </div>
      <% end %>
    </div>
  </div><!-- Blog item End -->
</article><!-- Blog Article End-->

app/views/shared/_block_recipe.erb
<style>
  .letter {
    color: black; /* Красный цвет символов */
    font-size: 100%; /* Размер шрифта в процентах */
  }
  .pad {
    margin-top: 5%; /* Отступ сверху */
  }
</style>
<div class="col-md-9" id="test">
  <p align="right"><%= rating_for @recipe, 'title', star: 5 %></p>
    <div class="col-md-3">
      <%= image_tag(@recipe.attachment.url(:medium), class:"img-responsive")%>
    </div>
    <div class="col-md-9">
      <h2> <%= @recipe.name %> </h2>
      <p><%= @recipe.short_description %> </p>
    </div>
    <div class="col-md-3">
    </div>
      <div class="col-md-9 pad">
        <ul>
          <li> <strong>Course:</strong> <%= @recipe.course %> </li>
          <li> <strong>Cuisine</strong> <%= @recipe.cuisine %> </li>
          <li> <strong>Skill level</strong> <%= @recipe.skill_level %> </li>
        </ul>
      </div>
      <div class="col-md-3">
      </div>
      <div class="col-md-9 pad">
        <table width="100%" cellspacing="0" border="0">
          <tr>
            <th> Servings </th>
            <th> Prep time </th>
            <th> Cook time </th>
          </tr>
          <tr>
            <td><%= @recipe.servings %> people </td>
            <td>  <%= @recipe.prep_time %> minutes </td>
            <td> <%= @recipe.cook_time %> minutes </td>
          </tr>
        </table>
      </div>
      <div class="col-md-9">
        <h3> Ingredients </h3>
      </div>
      <div class="col-md-9">
        <table width="80%" cellspacing="0" border="0">
          <% @recipe.ingredient.to_a.each do |element| %>
            <tr>
              <td>
                <%= element.find { |h| h['quantity'] }['quantity'] %>
                <%= element.find { |h| h['mera'] }['mera'] %>
              </td>
              <td>
                <%= element.find { |h| h['name'] }['name'] %>
                <%= element.find { |h| h['extra'] }['extra'] %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="col-md-9">
        <h3> Instructions </h3>
      </div>
        <% @recipe.instruction.to_a.each do |element| %>
          <div class="col-md-9">
            <ul>
              <li><%= element.find { |h| h['step'] }['step'] %> </li>
            </ul>
          </div>
        <% end %>
        <div class="col-md-9">
          <h4>Recipe Notes</h4>
          <%= raw @recipe.note %>
        </div>
</div>

app/views/shared/_devise.erb
<div class ="users">
<% if user_signed_in? %>
    <span>Hello, <%= current_user.email %></span>
    <span><%= link_to 'Home', root_path %></span>
    <span><%= link_to 'Profile', user_path(current_user) %></span>
    <span><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></span>
    <p><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %> </p>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>
<% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="footer-inner text-center">
          <ul class="footer-menu">
            <li>
              <%= link_to 'Home', root_path %>
            </li>
            <li>
              <%= link_to 'Posts', posts_path %>
            </li>
            <li>
              <%= link_to 'Recipes', recipes_path%>
            </li>
          </ul>
          <div class="copyright">
            <p> © 2016. Developed by </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_form_post.html.erb
<!--<div class="container">-->
<div class="row">
  <div class="col-md-12">
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@post.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
              <span class="glyphicon glyphicon-file"></span> POST NEW ARTICLE </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
          <div class="panel-body">
            <div class="row">
              <div class="col-md-9">
                <div class="form-group">
                  <%= form_for @post do |f| %>
                    <%= f.text_field :title, class: 'form-control', placeholder: :title %>
                </div>
                  <div class="form-group">
                    <%= f.text_field :name, class: 'form-control', placeholder: :name %>
                  </div>
                    <div class="form-group">
                      <%= f.cktext_area :content, ckeditor: {language: 'en'} %>
                    </div>
              </div>
                <div class="col-md-3">
                  <div class="well well-sm well-primary">
                    <div class="form-group">
                      <label for="form-control">
                        Post status
                      </label>
                        <%= f.select :post_status, options_for_select(article_status_all, selected_key = f.object.post_status), {}, class: 'form-control' %>
                      <div class="form-group">
                        <label for="form-control"> Shedule date publish </label>
                        <% if @post.post_status == "ready for publish" %>
                          <p><%= f.date_select :schedule_date %></p>
                           or
                           <p><input type="checkbox" name="schedule_box" value="immediately">IMMEDIATELY<Br></p>
                        <% end %>
                      </div>
                      <div class="form-group">
                        <label for="form-control"> Category </label>
                          <%= f.select :category_id, options_for_select(Category.all.map { |u| [u.name, u.id] }),{}, class: "form-control" %>
                      </div>
                        <%= f.label :tag_list, "Tags (separated by commas)" %><br />
                        <%= f.text_field :tag_list, class: 'form-control', placeholder: :tags %>
                    </div>
                      <%= f.submit 'Save', class: 'btn btn-success btn-sm' %>
                  <% end %>
                 </div>
                  <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <div id="asignee" class="form-group">
                          <%unless @post_collaborator.nil?%>
                          <%= form_for(@post_collaborator, :html => {:id => "assign"} ) do |f| %>
                            <%= f.select :user_collaborator_id, options_for_select(User.where('role_id=? or role_id=?', '2', '3').map { |u| [u.email, u.id] }),{}, class: "form-control" %>
                            <%= f.hidden_field :post_id, :value => @post.id%>
                            <% if check_post_coll_user == true %>
                              <%= f.submit 'Add to collaborator list' %>
                            <% end %>
                          <% end %>
                              <% end %>
                          <% if check_post_coll_user == true %>
                          <label for="form-control">
                            Post collaborators (click to delete)
                          </label>
                          <% end %>
                            <% @post.post_collaborators.each do |post_collaborator|%>
                              <div class="form-control">
                                <% post_collaborator %>
                                <% u = User.find(post_collaborator.user_collaborator_id) %>
                                <%= link_to  "#{u.email}", post_collaborator_path(post_collaborator),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %>
                              </div>
                            <% end %>
                        </div>
                          <div class="form-group">
                            <label for="form-control">Revision</label>
                            <select class="form-control" id="select_version">
                              <% @post.versions.reverse.each do |version| %>
                                <% unless version.event == 'create' %>
                                  <option value="<%= version.id %>"> <%= version.created_at %>
                                    Event: <%= version.event %></option>
                                <% end %>
                              <% end %>
                            </select>
                            <button id="show_version">Show</button>
                          </div>
                         <!--collaborator end-->
                        <% if check_post_coll_user == true %>
                          <%= form_for @post do |f| %>
                            <%= f.hidden_field :secret, :value => @gen%>
                            <%= f.submit 'Generate Secret URL' %>
                          <% end %>
                          <div id="content"> <%= @secret_url %> </div>
                          <button class="copy" title="content">Copy link</button>
                        <% end %>
                      </div>
                      <% if current_user.role_id == 2 %>
                          <%= form_for PostCollaborator.new  do |f| %>
                              <%= f.hidden_field :post_id, :value =>  @post.id  %>
                              <%= f.hidden_field :user_collaborator_id, :value =>  current_user.id %>
                              <td><%= f.submit 'add me as collaborator' %> </td>
                          <% end %>
                      <% end%>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
      <!--Comments block-->
      <% unless @post.nil? or @comment_block.nil? %>
        <div class="col-md-9" id="">
          <div id="comments_list">
            <div class="container  col-lg-12 col-md-12 col-sm-12" id="comments_list_inner">
              <div class="TITLE-com col-lg-12 col-md-12 col-sm-12 text-center"><strong>COMMENTS</strong>
                <div class="pull-right" data-toggle="modal" data-target="#widgetsettings"><i class="fa fa-cog"></i>
                </div>
              </div>
              <div class="container border comment-bg col-lg-12 col-xs-12">
                <% @post_comments.each do |comment| %>
                  <div class="comment">
                    <div class="comment-bg">
                      <div class="comment-item">
                        <div class="comment-txt">
                          <% unless comment.collaborate_user.blank?%>
                            <%= link_to comment.collaborate_user, user_path(User.find_by_email(comment.collaborate_user).id) %>
                          <% end %>
                          <%= comment.body %>
                        </div>
                        <div class="comment-name"> <%= current_user.email %>
                          (<%= comment.created_at.strftime("%d/%m/%Y %H:%M") %>)
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
              <%= js_will_paginate @post_comments %>
            </div>
          </div>
          <%= form_for([@post, @comment_block]) do |f| %>
            <p> <%= f.text_area :body, rows: 5, style: style="margin: 0px; width: 905px; height: 106px;" %> </p>
            <% if check_post_coll_user == true %>
              <p> <%= f.submit 'comment' %> </p>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% unless @post.nil? or @comment_block.nil? %>
  <script type="text/javascript">
    $(document).ready(function () {
      $('#show_version').click(function () {
        var url = '<%=edit_post_path(@post)%>/' + $('#select_version').val();
        document.location = url;
      });

      $("#comments_list").on("click", "a[paginate=true]", function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        $("#comments_list").load(url + ' #comments_list_inner')
      });

      function SelectContent(element) {
        var doc = document
            , text = doc.getElementById(element)
            , range, selection
            ;
        if (doc.body.createTextRange) {
          range = document.body.createTextRange();
          range.moveToElementText(text);
          range.select();
        } else if (window.getSelection) {
          selection = window.getSelection();
          range = document.createRange();
          range.selectNodeContents(text);
          selection.removeAllRanges();
          selection.addRange(range);

        }
        document.execCommand('Copy');
      }
      $(".copy").click(function(){

        SelectContent( $(this).attr('title'));
      });
    });
  </script>
<% end %>

app/views/shared/_list_post.erb
<!-- Content Start -->
<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <!-- Blog Article Start-->
        <% @posts.each do |post| %>
          <%= render 'shared/article_block', :post => post %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_list_recipe.erb
<!-- Content Start -->
<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <!-- Blog Article Start-->
        <% @recipes.each do |post| %>
            <%= render 'shared/article_block', :post => post %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_single.erb
<p id="notice">
  <%= notice %></p>
<!-- Content Start -->
<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <!-- Blog Article Start-->
        <article>
          <!-- Blog item Start -->
          <div class="blog-item-wrap">
            <!-- Post Format icon Start -->
            <div class="post-format">
              <span><i class="ico-bookmark"></i></span>
            </div>
            <!-- Post Format icon End -->
            <h2> <%= link_to @post.title, post_path(@post) %> </h2>
            <!-- Entry Meta Start-->
            <div class="entry-meta">
              <% unless @post.user.blank? %>
                <span class="meta-part"><i class="ico-user"></i> <%= link_to @post.user.user_nicename, authors_path(@post.user.user_nicename) %> </span>
              <% end %>
              <span class="meta-part"><i class="ico-calendar-alt-fill"></i>  </span> <%= @post.created_at %>
              <span class="meta-part"><i class="ico-tag"></i>Tags: <%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></span>
              <% unless @post.category.blank? %>
                <span class="meta-part"><i class="ico-tag"></i> Category: <%= link_to @post.category.name, category_path(@post.category.slug) %> </span>
              <% end %>
              <span class="meta-part"><i class="ico-tag"></i> Status:  </span> <%= @post.post_status %>
              <!--class="ico-tag"  class="ico-comments-->
            </div><!-- Entry Meta End-->
            <!-- Feature inner Start -->
            <div class="feature-inner">
            </div><!-- Feature inner End -->
            <!-- Post Content Start -->
            <div class="post-content">
              <p> <% @post.attachments.where(main_image: "yes").each do |attachment| %>
                  <%= image_tag attachment.attachment.url %> <% end %></p>
              <p><%= raw@post.content %> </p>
            </div><!-- Post Content End -->
            <div class="entry-more">
              <div class="pull-left">
                <a class="btn btn-common" href="<%=edit_post_path(@post)%>">Edit <i class="ico-arrow-right"></i></a>
              </div>
              <div class="share-icon pull-right">
                <span class="socialShare"></span>
              </div>
            </div>
          </div><!-- Blog item End -->
        </article><!-- Blog Article End-->
      </div>
      <div class="col-md-4">
        <!-- Blog Article Start-->
        <% @post.similar_posts.each do |similar|%>
          <% unless similar.title.blank? %>
            <article>
              <!-- Blog item Start -->
              <div class="blog-item-wrap">
                <!-- Post Format icon Start -->
                <div class="post-format">
                  <span><i class="ico-bookmark"></i></span>
                </div>
                <div class="post-content">
                  <%=  link_to similar.title, post_path(similar) %>
                  <p> <% main_image = similar.attachments.where(main_image: "yes").first %>
                    <%unless main_image.nil?%>
                      <%= image_tag main_image.attachment.url %> </p>
                    <% end %>
                </div><!-- Post Content End -->
                <!-- Post Format icon End -->
                <!-- Entry Meta Start-->
                <div class="entry-more">
                  <div class="share-icon pull-right">
                    <span class="socialShare"></span>
                  </div>
                </div>
              </div><!-- Blog item End -->
            </article><!-- Blog Article End-->
          <% end %>
            <%#= will_paginate similar%>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/shared/_single_recipe.erb
<p id="notice">
  <%= notice %></p>
<!-- Content Start -->
<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <!-- Blog Article Start-->
        <article>
          <!-- Blog item Start -->
          <div class="blog-item-wrap">
            <!-- Post Format icon Start -->
            <div class="post-format">
              <span><i class="ico-bookmark"></i></span>
            </div>
            <!-- Post Format icon End -->
            <h2> <%= link_to @recipe.title, recipe_path(@recipe) %> </h2>
            <!-- Entry Meta Start-->
            <div class="entry-meta">
              <% unless @recipe.user.blank? %>
                  <span class="meta-part"><i class="ico-user"></i> <%= link_to @recipe.user.user_nicename, authors_path(@recipe.user.user_nicename) %> </span>
              <% end %>
              <span class="meta-part"><i class="ico-calendar-alt-fill"></i>  </span> <%= @recipe.created_at %>
              <span class="meta-part"><i class="ico-tag"></i>Tags: <%= raw@recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></span>
              <% unless @recipe.category.blank? %>
                  <span class="meta-part"><i class="ico-tag"></i> Category: <%= link_to @recipe.category.name, category_path(@recipe.category.slug) %> </span>
              <% end %>
              <span class="meta-part"><i class="ico-tag"></i> Status:  </span> <%= @recipe.post_status %>
              <!--class="ico-tag"  class="ico-comments-->
            </div><!-- Entry Meta End-->
            <!-- Feature inner Start -->
            <div class="feature-inner">
            </div><!-- Feature inner End -->
            <!-- Post Content Start -->
            <div class="post-content">
              <p> <% @recipe.attachments.where(main_image: "yes").each do |attachment| %>
                  <%= image_tag attachment.attachment.url %> <% end %></p>
              <p><%= raw@recipe.content %> </p>
            </div><!-- Post Content End -->
            <div class="entry-more">
              <div class="pull-left">
                <a class="btn btn-common" href="<%=edit_recipe_path(@recipe)%>">Edit <i class="ico-arrow-right"></i></a>
              </div>
              <div class="share-icon pull-right">
                <span class="socialShare"></span>
              </div>
            </div>
          </div><!-- Blog item End -->
        </article><!-- Blog Article End-->
      </div>
      <div class="col-md-4">
        <!-- Blog Article Start-->
        <% @recipe.similar_posts.each do |similar|%>
          <%unless similar.title.blank?%>
            <article>
              <!-- Blog item Start -->
              <div class="blog-item-wrap">
                <!-- Post Format icon Start -->
                <div class="post-format">
                  <span><i class="ico-bookmark"></i></span>
                </div>
                <div class="post-content">
                  <%=  link_to similar.title, recipe_path(similar) %>
                  <p> <% main_image = similar.attachments.where(main_image: "yes").first %>
                    <%unless main_image.nil?%>
                      <%= image_tag main_image.attachment.url %> </p>
                    <% end %>
                </div><!-- Post Content End -->
                <!-- Post Format icon End -->
                <!-- Entry Meta Start-->
                <div class="entry-more">
                  <div class="share-icon pull-right">
                    <span class="socialShare"></span>
                  </div>
                </div>
              </div><!-- Blog item End -->
            </article><!-- Blog Article End-->
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user_info.html.erb
<!-- Fixed navbar -->

<nav class="navbar navbar-default ">
  <div class="container">
    <div class="navbar-header dropdown">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand user-img bg-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>-->
      <div class="pull-left user-info">
        <p class="no-pad">  </p>

      </div>


    </div>
    <div class="block_search">
      <div class="wrap">
        <%= form_tag(results_path, method: :get, role: 'search') do %>
            <%= radio_button_tag(:search, "posts_recipes", checked = true) %>
            <%= label_tag(:posts_recipes, "posts + recipes") %>
            <%= radio_button_tag(:search, "profiles") %>
            <%= label_tag(:profiles, "profiles") %>
            <%= text_field_tag :query, params[:query], class: "searchTerm" %>
            <%= button_tag(type: "submit", class: "searchButton",  name: nil) do %>
                <i class="fa fa-search"></i>
            <% end %>
          <% end %>
      </div>
   </div>

    <% if user_signed_in? %>
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <button href="#" class="dropdown-toggle btn btn-default navbar-btn btn-lg" data-toggle="dropdown" id="pricing-btn" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.user_nicename %> <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Home', root_path %></li>
                <% if current_user.role.name == "admin" || current_user.role.name == "editor" %>
                  <li><%= link_to 'Dashboard', (dashboard_path) %></li>
                <% end %>
                <li><%= link_to 'Profile', user_path(current_user) %></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        </div>
    <% end %>

    <!-- /.navbar-collapse -->

    <!--/.nav-collapse -->
  </div>
</nav>

<script>
  $(window).on('scroll',function(e){
    if (this.scrollY> 0) {
      $("nav.navbar").addClass("nav-scroll");
    } else {
      $("nav.navbar").removeClass("nav-scroll");
    }
  });
</script>