config/routes.rb
require 'domain_constraint'

Rails.application.routes.draw do
  constraints DomainConstraint.new('dima') do
    root :to => 'recipes#index'
  end
  post '/rate' => 'rater#create', :as => 'rate'

  resources :recipes do
    resources :comment_blocks
  end

  resources :posts do
    resources :comment_blocks
  end

  resources :foodiye_posts , :path => "pins" do
    resources :comment_blocks
  end


  resources :post_collaborators
  resources :user_collaborators

  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  get 'users' => 'foodiye_posts#members'
  get 'get_title' => 'foodiye_posts#get_title'
  get 'hand/:id' => 'handler#hand'
  get 'tags/:tag', to: 'posts#index', as: 'tag'
  get 'authors/:user_nicename' => 'posts#authors', as: 'authors'
  get 'category/:slug' => 'posts#categories', as: 'category'
  post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users, :only => [:show]
  get '/posts/versions/history/:id' => 'versions#history', as: :posts_history
  get '/posts/:id/edit/:version_id' => 'posts#edit', as: :posts_version
  get '/recipes/:id/edit/:version_id' => 'recipes#edit', as: :recipes_version

  scope  'admin' do
  get '/dashboard' => 'admin_panel#main_page'
  get '/black_list_domain' => 'admin_panel#black_list'
  post '/black_list_domain' => 'admin_panel#add_black_list'
  delete '/black_list_domain' => 'admin_panel#destroy_black_list', :as => 'destroy'
  end

  get 'results', to: 'results#index', as: 'results'

  mount SimpleFormMarkdownEditor::Engine => "/"
  #reputation system
  delete  'likes/:resource_name/:resource_id' => 'likes#destroy', :as => 'unlike'
  post    'likes/:resource_name/:resource_id' => 'likes#create',  :as => 'like'

end

app/models/foodiye_post.rb
class FoodiyePost < ApplicationRecord
  belongs_to :user
  has_many   :comment_blocks
  has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100#" }
  validates_attachment_content_type :attachment, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :title, :description, presence: true
  validates :video_url, presence: true, :unless => lambda { |o| o.post_type != 'video' }
  validates :photo_link, presence: true, :unless => lambda { |o| o.post_type != 'photo' }, if: :attachment_file_nil?
  include Likeable

  protected
  def attachment_file_nil?
    self.attachment_file_size == nil
  end

end

app/controllers/foodiye_posts_controller.rb
class FoodiyePostsController < ApplicationController
  require 'uri/http'
  require 'nokogiri'
  require 'open-uri'

  layout 'foodiye'
  before_action :set_foodiye_post, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:index, :show]
  before_action :authenticate_user!, :except => [:show, :index  ]
  before_action :require_permission, :only => [:edit, :update]
  before_action :destroy_if_foodiye_admin, :only => [:destroy]
  before_action :check_blacklist, :only => [:create, :update]

  # GET /foodiye_posts
  def index
    @foodiye_posts = FoodiyePost.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
  end

  # GET /foodiye_posts/1
  def show
    @foodiye_post = FoodiyePost.find(params[:id])
  end

  # GET /foodiye_posts/new
  def new
    @foodiye_post = FoodiyePost.new
  end

  # GET /foodiye_posts/1/edit
  def edit
    @foodiye_posts_comment = CommentBlock.where(foodiye_post_id: @foodiye_post).order('created_at DESC')
  end

  # POST /foodiye_posts
  def create
    @foodiye_post = FoodiyePost.new(foodiye_post_params)
    # check_blacklist(@foodiye_post.photo_link.to_s)
    respond_to do |format|
      if @foodiye_post.save
        unless @foodiye_post.video_url.blank?
          convert = @foodiye_post.video_url.gsub('watch?v=', 'embed/')
          @foodiye_post.video_url = convert
          @foodiye_post.save!
        end
        format.html { redirect_to @foodiye_post, notice: 'Foodiye post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /foodiye_posts/1
  def update
    respond_to do |format|
      if @foodiye_post.update(foodiye_post_params)
        unless @foodiye_post.video_url.blank?
          convert = @foodiye_post.video_url.gsub('watch?v=', 'embed/')
          @foodiye_post.video_url = convert
          @foodiye_post.save!
        end
        format.html { redirect_to @foodiye_post, notice: 'Foodiye post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /foodiye_posts/1
  def destroy
    @foodiye_post.destroy
    respond_to do |format|
      format.html { redirect_to foodiye_posts_url, notice: 'Foodiye post was successfully destroyed.' }
    end
  end

  def members
    @foodiye_posts = FoodiyePost.all.order("created_at DESC")
    @users = User.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 30)
  end

  def get_title
    url = params[:data_value]
    doc = Nokogiri::HTML(open(url))
    doc.at_css('title') ? title = doc.at_css('title').text : title = "no title suggested"
    title
    if title != "no title suggested"
      data = {:message => title}
      render :json => data, :status => :ok
    else
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodiye_post
      @foodiye_post = FoodiyePost.find(params[:id])
    end

  def check_blacklist
    if action_name == "new" or action_name == "create"
      @foodiye_post = FoodiyePost.new(foodiye_post_params)
    else  action_name == "update"
       @foodiye_post.assign_attributes(params[:foodiye_post])
    end

    blacklist = Blacklist.all
    array = []
    blacklist.each {|name| array.push(name.domain) }
    unless @foodiye_post.photo_link.blank?
      myUri = URI.parse(@foodiye_post.photo_link.to_s).host
    else @foodiye_post.photo_link.blank?
      myUri = URI.parse(@foodiye_post.video_url.to_s).host
    end
    array.each do |black_url|
      if myUri == black_url
        redirect_to :back, notice: 'Can`t save. URL found in blacklist!'
      else
      end
    end
  end

  def require_permission
     if current_user.id != FoodiyePost.find(params[:id]).user_id
        redirect_to foodiye_posts_path
        #Or do something else here
     end
  end

  def destroy_if_foodiye_admin
    unless current_user.role_id == 2
      redirect_to foodiye_posts_path, notice: 'You have no permitions'
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foodiye_post_params
      params.require(:foodiye_post).permit!
    end
end

app/helpers/foodiye_posts_helper.rb
module FoodiyePostsHelper
end

app/views/foodiye_posts/edit.html.erb
<%= render 'shared/foodiye/form_edit_foodiye', foodiye_post: @foodiye_post %>

app/views/foodiye_posts/index.html.erb
<div class="content">
  <div class="wrap">
    <div id="main" role="main">
      <p id="notice"> <%= notice %> </p>
      <ul id="tiles">
        <!-- These are our grid blocks -->
        <% @foodiye_posts.each do |foodiye_post|%>
          <li>
            <% if foodiye_post.post_type == "photo" %>
              <% if foodiye_post.attachment.url.present? or (foodiye_post.attachment.url.present? && foodiye_post.photo_link.present?) %>
                <%= link_to image_tag(foodiye_post.attachment.url), foodiye_post_path(foodiye_post) %>
              <% elsif foodiye_post.photo_link.present? %>
                 <%= link_to image_tag(foodiye_post.photo_link), foodiye_post_path(foodiye_post) %>
              <% end %>
            <% elsif foodiye_post.post_type == "video" %>
              <iframe width="278" height=auto  src="<%= foodiye_post.video_url %>" frameborder="0" ></iframe>
            <% end %>
            <!--<img src="images/img1.jpg" width="282" height="118">-->
            <div class="post-info">
              <div class="post-basic-info">
                <h3> <%= link_to foodiye_post.title, foodiye_post_path(foodiye_post) %> </h3>
                <p> <%= foodiye_post.description %></p>
              </div>
              <% if user_signed_in? %>
                  <% if current_user.id == foodiye_post.user_id %>
                    <%= link_to 'Edit', edit_foodiye_post_path(foodiye_post) %>
                    <%= link_to 'Destroy', foodiye_post_path(foodiye_post), method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
                  <% if current_user.role_id == 2 %>
                      <%= link_to 'Destroy as admin', foodiye_post_path(foodiye_post), method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>

                  <% if foodiye_post.user.present? %>
                    <%= link_to foodiye_post.user.user_nicename, user_path(foodiye_post.user)%>
                  <% end %>
                <% if current_user.likes? foodiye_post %>
                   <%= unlike_link_for(foodiye_post)  %>
                <%  else %>
                   <%= like_link_for(foodiye_post) %>
                <% end %>
                Like count <%= foodiye_post.like_count  %>
              <% end %>
              <% foodiye_post_comment = CommentBlock.where(foodiye_post_id: foodiye_post.id) %>
              <% foodiye_post_comment.each do |comment|%>
              <div class="post-info-rate-share">
                <% user = User.find(comment.user_id)%>
                <% if user.present? %>
                  <%= link_to user.user_nicename, user_path(user) %>
                <% end %>
                  <% if comment.attachment_file_size != nil %>
                    <%= image_tag comment.attachment.url(:thumb) %>
                  <% end %>
                <%= comment.body %>
              </div>
              <% end %>
              <% if user_signed_in? %>


                  <div class="post-info-rate-share">
                    <div>
                      <% comment_block = CommentBlock.new %>
                      <%= form_for([foodiye_post, comment_block]) do |f| %>
                        <p> <%= f.text_area :body, rows: 1, style: "margin: 0px; width: 100%; height: 40px;" %> </p>
                        <%= f.file_field :attachment, as: :file %>
                        <p> <%= f.button 'comment', class: "btn btn-primary" %> </p>
                      <% end %>
                    </div>

                    <div class="post-share">
                      <span>  </span>
                    </div>
                    <div class="clear"> </div>
                  </div>
              <% end %>
            </div>
          </li>
        <% end %>
        <!-- End of grid blocks -->
      </ul>
    </div>
  </div>
</div>
<%= will_paginate  @foodiye_posts%>
<!---//End-content---->
<!----wookmark-scripts---->
  <script type="text/javascript">
    (function ($){
      var $tiles = $('#tiles'),
        $handler = $('li', $tiles),
        $main = $('#main'),
        $window = $(window),
        $document = $(document),
        options = {
          autoResize: true, // This will auto-update the layout when the browser window is resized.
          container: $main, // Optional, used for some extra CSS styling
          offset: 20, // Optional, the distance between grid items
          itemWidth:280 // Optional, the width of a grid item
        };
      /**
       * Reinitializes the wookmark handler after all images have loaded
       */
      function applyLayout() {
        $tiles.imagesLoaded(function() {
          // Destroy the old handler
          if ($handler.wookmarkInstance) {
            $handler.wookmarkInstance.clear();
          }
          // Create a new layout handler.
          $handler = $('li', $tiles);
          $handler.wookmark(options);
        });
      }
      /**
       * When scrolled all the way to the bottom, add more tiles
       */
      // Call the layout function for the first time
      applyLayout();
      // Capture scroll event.
      $window.bind('scroll.wookmark', onScroll);
    })(jQuery);
  </script>
<!----//wookmark-scripts---->

app/views/foodiye_posts/members.html.erb
<div class="content">
  <div class="wrap">
    <div id="main" role="main">
      <ul id="tiles">
        <!-- These are our grid blocks -->
        <% @users.each do |user|%>
            <% unless user.email.nil? %>
          <li >
            <% if user.avatar.present? %>
              <%= image_tag user.avatar.url %>
            <% elsif user.fb_image_url.present?%>
              <%= image_tag user.fb_image_url %>
            <% else %>
              <%= image_tag ('default_user_icon.jpg') %>
            <% end %>
            <div class="post-info">
              <h3> <%= link_to user.user_nicename, user_path(user) %> </h3>
            </div>
          </li>
        <% end %>
            <% end %>
        <!-- End of grid blocks -->
      </ul>
    </div>
  </div>
</div>
<%= will_paginate @users %>

<!---//End-content---->
<!----wookmark-scripts---->
<script type="text/javascript">
  (function ($){
    var $tiles = $('#tiles'),
        $handler = $('li', $tiles),
        $main = $('#main'),
        $window = $(window),
        $document = $(document),
        options = {
          autoResize: true, // This will auto-update the layout when the browser window is resized.
          container: $main, // Optional, used for some extra CSS styling
          offset: 20, // Optional, the distance between grid items
          itemWidth:280 // Optional, the width of a grid item
        };
    /**
     * Reinitializes the wookmark handler after all images have loaded
     */
    function applyLayout() {
      $tiles.imagesLoaded(function() {
        // Destroy the old handler
        if ($handler.wookmarkInstance) {
          $handler.wookmarkInstance.clear();
        }
        // Create a new layout handler.
        $handler = $('li', $tiles);
        $handler.wookmark(options);
      });
    }
    /**
     * When scrolled all the way to the bottom, add more tiles
     */
      // Call the layout function for the first time
    applyLayout();
    // Capture scroll event.
    $window.bind('scroll.wookmark', onScroll);
  })(jQuery);
</script>
<!----//wookmark-scripts---->

app/views/foodiye_posts/new.html.erb
<%= render 'shared/foodiye/form_foodiye', foodiye_post: @foodiye_post %>

app/views/foodiye_posts/show.html.erb
<p id="notice"><%= notice %></p>
<!---start-content---->
<div class="row">
  <div class="col-md-9">
    <div class="content">
      <div class="wrap">
        <div class="single-page">
          <div class="single-page-artical">
            <div class="artical-content">
              <%= link_to 'Back', foodiye_posts_path %>
              <% if @foodiye_post.post_type == "photo" %>
                  <% if @foodiye_post.attachment.url.present? or (@foodiye_post.attachment.url.present? && @foodiye_post.photo_link.present?) %>
                      <%= link_to image_tag(@foodiye_post.attachment.url), foodiye_post_path(@foodiye_post) %>
                  <% elsif @foodiye_post.photo_link.present? %>
                      <%= link_to image_tag(@foodiye_post.photo_link), foodiye_post_path(@foodiye_post) %>
                  <% end %>
                  <h3> <%= @foodiye_post.title%> </h3>
                  <p> <%= @foodiye_post.description %></p>
              <% elsif @foodiye_post.post_type == "video" %>
                  <iframe width=100% height="500"  src="<%= @foodiye_post.video_url %>" frameborder="0" ></iframe>
                  <h3> <%= @foodiye_post.title%> </h3>
                  <p> <%= @foodiye_post.description %></p>
              <% else @foodiye_post.post_type == "topic" %>
                  <h3> <%= @foodiye_post.title%> </h3>
                  <p> <%= @foodiye_post.description %></p>
              <% end %>
            </div>
            <%= link_to 'Edit', edit_foodiye_post_path(@foodiye_post) %> |
            <%= link_to 'Destroy', foodiye_post_path(@foodiye_post), method: :delete, data: { confirm: 'Are you sure?' } %>

            <!--<div class="artical-links">-->
            <!--<div class="share-artical">-->
            <!--<div class="clear"></div>-->
          </div>
          <!---start-comments-section--->
          <div class="comment-section">
            <div class="grids_of_2">
              <h2>Comments</h2>
              <div class="grid1_of_2">
                <% foodiye_post_comment = CommentBlock.where(foodiye_post_id: @foodiye_post.id) %>
                <% foodiye_post_comment.each do |comment|%>
                <% user = User.find(comment.user_id)%>
                  <div class="grid_text">
                    <h4 class="style1 list"> <%= "#{user.user_nicename}: " %> </h4>
                    <h3 class="style"> <%= comment.created_at %> </h3>
                    <p class="para top">  <%= comment.body %> </p>
                  </div>
                  <div class="clear"></div>
                <% end %>
              </div>
              <div class="artical-commentbox">
                <h2>Leave a Comment</h2>
                <div class="table-form">
                  <% comment_block = CommentBlock.new %>
                  <%= form_for([@foodiye_post, comment_block]) do |f| %>
                    <p> <%= f.text_area :body, rows: 1, style: "margin: 0px; width: 100%; height: 40px;" %> </p>
                    <%= f.file_field :attachment, as: :file %>
                    <p> <%= f.button 'comment', class: "btn btn-primary" %> </p>
                  <% end %>
                </div>
                <div class="clear"></div>
              </div>
            </div>
          </div>
          <!---//End-comments-section--->
        </div>
      </div>
    </div>
  </div>
</div>
<!----start-footer--->
<div class="footer">
  <p></p>
</div>
<!----//End-footer--->
<!---//End-wrap---->